#!/bin/bash

EMAIL=bjasper@gmail.com
ARGS=$(getopt r: "$@")

eval set -- "$ARGS"

case $1 in

  # Reminder
  -r)
    REMINDER=$2
    TODO=${@:4}
    FOLLOWUP_EMAIL="$REMINDER@followup.cc"

    echo "Added todo '$TODO' with reminder"
    echo "$TODO" | mail -s "$TODO" -c $FOLLOWUP_EMAIL $EMAIL
    ;;

  # Regular
  *)
    TODO=${@:2}
    echo "Added todo '$TODO'"
    echo "$TODO" | mail -s "$TODO" $EMAIL
    ;;
esac
